name: ItemLimiter
version: 1.0-SNAPSHOT
main: de.priyme.itemlimiter.ItemLimiter
api-version: 1.21
permissions:
  itemlimiter.admin:
    description: Admin permissions
    default: op
commands:
  limit:
    description: Open the Limit GUI
    permission: itemlimiter.admin
